# Aider configuration for SpecSafe projects
# https://aider.chat/docs/config/aider_conf.html
# Version: 1.0.0

# Always read PROJECT_STATE.md for context
read:
  - PROJECT_STATE.md
  - README.md
  - CONVENTIONS.md

# Use .aiderignore for file exclusions (gitignore syntax)
aiderignore: .aiderignore

# Don't add .gitignore'd files to aider's scope
add-gitignore-files: false
