/**
 * Generate a delta spec template
 * @param deltaId - Delta spec identifier
 * @param baseSpecId - Base spec this delta applies to
 * @param author - Author name
 * @param date - Optional date for testability (defaults to today)
 * @returns Delta spec template content
 */
export function generateDeltaTemplate(
  deltaId: string, 
  baseSpecId: string, 
  author: string,
  date?: string
): string {
  const createdDate = date || new Date().toISOString().split('T')[0];
  
  return `# Delta Spec: ${deltaId}

**Base Spec:** ${baseSpecId}
**Created:** ${createdDate}
**Author:** ${author}
**Description:** Brief description of changes

---

## ADDED Requirements

### FR-NEW-1
**Priority:** P1

[Requirement text here]

- Scenario: [description]

---

## MODIFIED Requirements

### FR-EXISTING-1
**Priority:** P0

[New requirement text] ← (was [old requirement text])

---

## REMOVED Requirements

- FR-OLD-1
- FR-OLD-2

---

*Generated by SpecSafe Delta System*
`;
}

/**
 * Generate a README file explaining the delta spec format
 * @returns Markdown content for delta spec documentation
 */
export function generateDeltaReadme(): string {
  return `# Delta Specs

Delta specs describe **incremental changes** to existing specs (brownfield projects).

## Workflow

1. **Create Delta**: \`specsafe delta <spec-id>\`
2. **Preview Changes**: \`specsafe diff <spec-id>\`
3. **Apply Delta**: \`specsafe apply <spec-id>\`
`;
}
