export function generateDeltaTemplate(deltaId: string, baseSpecId: string, author: string): string {
  return `# Delta Spec: ${deltaId}

**Base Spec:** ${baseSpecId}
**Created:** ${new Date().toISOString().split('T')[0]}
**Author:** ${author}
**Description:** Brief description of changes

---

## ADDED Requirements

### FR-NEW-1
**Priority:** P1

[Requirement text here]

- Scenario: [description]

---

## MODIFIED Requirements

### FR-EXISTING-1
**Priority:** P0

[New requirement text] ← (was [old requirement text])

---

## REMOVED Requirements

- FR-OLD-1
- FR-OLD-2

---

*Generated by SpecSafe Delta System*
`;
}

export function generateDeltaReadme(): string {
  return `# Delta Specs

Delta specs describe **incremental changes** to existing specs (brownfield projects).

## Workflow

1. **Create Delta**: \`specsafe delta <spec-id>\`
2. **Preview Changes**: \`specsafe diff <spec-id>\`
3. **Apply Delta**: \`specsafe apply <spec-id>\`
`;
}
