/**
 * GitHub Copilot Adapter
 * Generates .github/copilot-instructions.md for GitHub Copilot
 */

import { BaseAgentAdapter } from './base.js';
import type { AgentDefinition, GeneratedFile, GenerateOptions } from '../types.js';
import { getRequiredAgentDefinition } from '../registry.js';

export class CopilotAdapter extends BaseAgentAdapter {
  readonly agent: AgentDefinition = getRequiredAgentDefinition('copilot');

  async generateConfig(projectDir: string, options?: GenerateOptions): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    files.push({
      path: '.github/copilot-instructions.md',
      content: `# SpecSafe - GitHub Copilot Instructions

${this.getMainContext()}

## Workflow Commands

Use \`@workspace /command\` to invoke SpecSafe workflow commands:

### @workspace /specsafe
${this.getCommandPrompt('specsafe')}

### @workspace /specsafe-explore
${this.getCommandPrompt('specsafe-explore')}

### @workspace /specsafe-new
${this.getCommandPrompt('specsafe-new')}

### @workspace /specsafe-spec
${this.getCommandPrompt('specsafe-spec')}

### @workspace /specsafe-test-create
${this.getCommandPrompt('specsafe-test-create')}

### @workspace /specsafe-test-apply
${this.getCommandPrompt('specsafe-test-apply')}

### @workspace /specsafe-verify
${this.getCommandPrompt('specsafe-verify')}

### @workspace /specsafe-done
${this.getCommandPrompt('specsafe-done')}

## Context Files

Always check these files before making changes:
- PROJECT_STATE.md - Current project status and active specs
- specs/active/*.md - Detailed specifications
- specsafe.config.json - Project configuration

## File Structure

\`\`\`
my-project/
├── specs/
│   ├── drafts/          # PRD stage specs
│   ├── active/          # In-progress specs
│   ├── archive/         # Completed specs
│   └── exploration/     # Research notes
├── src/
│   └── __tests__/       # Test files organized by spec
├── PROJECT_STATE.md     # Central status tracker
└── .github/
    └── copilot-instructions.md  # This file
\`\`\`

## Commit Messages

Always use this format:
\`\`\`
type(SPEC-ID): brief description

- Detailed change 1
- Detailed change 2

Refs: SPEC-ID
\`\`\`

Types: feat, fix, test, docs, refactor, chore

---
*Generated by SpecSafe v1.0*
`,
    });

    return files;
  }

  async generateCommands(projectDir: string, options?: GenerateOptions): Promise<GeneratedFile[]> {
    // Copilot doesn't use separate command files
    return [];
  }

  getInstructions(): string {
    return `GitHub Copilot Setup Complete!

File created:
- .github/copilot-instructions.md - SpecSafe workspace instructions

## Usage

1. Open your project in VS Code with GitHub Copilot
2. Use @workspace commands:
   - @workspace /specsafe - Check status
   - @workspace /specsafe-explore - Start exploration
   - @workspace /specsafe-new - Create spec
   - @workspace /specsafe-spec - Review/refine spec
   - @workspace /specsafe-test-create - Generate tests
   - @workspace /specsafe-test-apply - Implement
   - @workspace /specsafe-verify - Verify tests
   - @workspace /specsafe-done - Complete spec

Copilot will use the instructions in .github/copilot-instructions.md to guide suggestions.
`;
  }
}
