/**
 * Cursor Adapter
 * Generates .cursorrules for Cursor IDE
 */

import { BaseAgentAdapter } from './base.js';
import type { AgentDefinition, GeneratedFile, GenerateOptions } from '../types.js';
import { AGENT_DEFINITIONS } from '../registry.js';

export class CursorAdapter extends BaseAgentAdapter {
  agent: AgentDefinition = AGENT_DEFINITIONS.find((a) => a.id === 'cursor')!;

  async generateConfig(projectDir: string, options?: GenerateOptions): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    files.push({
      path: '.cursorrules',
      content: `# SpecSafe Rules for Cursor IDE v1.0
# Spec-Driven Development (SDD) Workflow
# https://github.com/luci-efe/specsafe

${this.getMainContext()}

## The SpecSafe Workflow Commands

When working on this project, follow the SDD workflow:

### @specsafe - Show Project Status
${this.getCommandPrompt('specsafe')}

### @specsafe-explore - Pre-Spec Exploration
${this.getCommandPrompt('specsafe-explore')}

### @specsafe-new - Initialize Spec with PRD
${this.getCommandPrompt('specsafe-new')}

### @specsafe-spec - Generate Detailed Spec
${this.getCommandPrompt('specsafe-spec')}

### @specsafe-test-create - Create Tests from Spec
${this.getCommandPrompt('specsafe-test-create')}

### @specsafe-test-apply - Apply Tests (Development Mode)
${this.getCommandPrompt('specsafe-test-apply')}

### @specsafe-verify - Verify and Iterate
${this.getCommandPrompt('specsafe-verify')}

### @specsafe-done - Complete and Archive
${this.getCommandPrompt('specsafe-done')}

## File Organization

my-project/
├── specs/
│   ├── drafts/          # PRD stage specs
│   ├── active/          # In-progress specs
│   ├── archive/         # Completed specs
│   └── exploration/     # Research notes
├── src/
│   └── __tests__/       # Test files organized by spec
├── PROJECT_STATE.md     # Central status tracker
└── .cursorrules        # This file

## Commit Message Format

type(SPEC-ID): brief description

- Detailed change 1
- Detailed change 2

Refs: SPEC-ID

Types: feat, fix, test, docs, refactor, chore
Example: feat(SPEC-20260212-001): add user authentication

---
*Version: 1.0*
*Generated by SpecSafe*
`,
    });

    return files;
  }

  async generateCommands(projectDir: string, options?: GenerateOptions): Promise<GeneratedFile[]> {
    // Cursor doesn't have separate command files - everything is in .cursorrules
    return [];
  }

  getInstructions(): string {
    return `Cursor IDE Setup Complete!

File created:
- .cursorrules - SpecSafe workflow rules

## Usage

1. Open your project in Cursor
2. Use @ mentions to invoke commands:
   - @specsafe - Check project status
   - @specsafe-explore - Start exploration
   - @specsafe-new - Create new spec
   - @specsafe-test-create - Generate tests
   - @specsafe-test-apply - Implement features
   - @specsafe-verify - Run tests
   - @specsafe-done - Complete spec

Cursor will follow the rules defined in .cursorrules to guide you through the workflow.
`;
  }
}
